### PR TITLE
Fix a number of exceptions due to bad unkown values

### PR DESCRIPTION
**Pull request by Olen**
This should take care of a lot of exceptions in the logs after upgrade to 2023.5

### CODE REVIEW

**Comment by mundschenk-at** [comment]
Looks like this didn't fix alle the issues. After updating to 2.1.1 and restarting, I am still getting log entries like these:

```
2023-05-06 15:33:47.580 ERROR (MainThread) [homeassistant.helpers.entity] Update for plant.calathea_ornata fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'unknown'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
await coro
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/plant/__init__.py", line 627, in update
and self.sensor_moisture.state != STATE_UNKNOWN
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
raise ValueError(
ValueError: Sensor sensor.calathea_ornata_soil_moisture has device class moisture, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)

```

**Comment by Olen** [comment]
I think you will get a few until all restored values have been overwritten by new data.
As soon as all sensors have received fresh data at least once, the problem should go away, I hope.
But I will keep monitoring my own logs to see if I have missed some "unknown"s

**Comment by mundschenk-at** [comment]
Still happens on every HA restart. I think the issue is that the raw sensor state (provided by MiFlora) is `unavailable` for a short amount of time on restart. Might be a race condition since your integration depends on the sensor values of another integration.

**Comment by Olen** [comment]
Yes. That is the issue. In this patch I have tried to work around it by setting my values to `None` if the parent is 'unknown', but I might have missed it on some code paths.

**Pull request merged**
