### PR TITLE
Fix ValueError

### LINKED ISSUE #76: Value error
The plant entity on my HA is not working fully correct. I do see it has all of the variables:

`species: Olea europaea
moisture_status: ok
temperature_status: ok
conductivity_status: Low
illuminance_status: ok
humidity_status: null
dli_status: Low
species_original: olea europaea
device_class: plant
entity_picture: /local/images/plants/olea europaea.jpg
friendly_name: Olijfboom1 `

but the plantcard is not displaying anything. It’s blank. When diving into the logs I could see the following:

`ValueError: Sensor sensor.olijfboom1_soil_moisture has device class moisture, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>) `

so maybe this has to do something with my plant entity not showing up correctly?

### PR DESCRIPTION
**Pull request by miguelangel-nubla**
Fixes #76

### CODE REVIEW

**Comment by Olen** [comment]
Please fix the code format errors, and I'll merge this and create a new release.

**Comment by Jano1312** [comment]
With 2.1.2-beta1 i get the following error when starting homeassistant:


```
Logger: homeassistant.setup
Source: components/plant/__init__.py:110
First occurred: 00:24:55 (1 occurrences)
Last logged: 00:24:55
Error during setup of component plant

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/plant/__init__.py", line 110, in async_setup
    for plant_name, plant_config in config[DOMAIN].items():
                                    ~~~~~~^^^^^^^^
KeyError: 'plant'
```

**Comment by Olen** [comment]
Please add it as an Issue, not as a comment to a closed PR.

Anyway - that sounds _very_ strange, as that code does not exist.  
It might have existed in a very old version, so please check what version you really have installed

**Comment by Jano1312** [comment]
Sorry, i'm relativ new in github, will do

**Pull request merged**
