### PR TITLE
Use openplantbooks service return_value

### LINKED ISSUE #80: Cannot set up
I have just installed this integration but am getting the following error:

`This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/plant/plant_helpers.py:105
Integration: Plant monitor (documentation, issues)
First occurred: 8:52:19 PM (1 occurrences)
Last logged: 8:52:19 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 297, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 393, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/config_flow.py", line 115, in async_step_user
    return await self.async_step_select_species()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/config_flow.py", line 186, in async_step_select_species
    search_result = await plant_helper.openplantbook_search(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/plant_helpers.py", line 105, in openplantbook_search
    plant_search = await self.hass.services.async_call(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ServiceRegistry.async_call() got an unexpected keyword argument 'limit'
`
I'm running Home Assistant 2023.7

### LINKED ISSUE #82: Did not find  in OpenPlantbook.
so ive trying to add 2 plants dracaena braunii and yucca elephantipes and for both im getting "Did not find «dracaena braunii» in OpenPlantbook. Using default values for thresholds."  using 2.2.0-beta1

Opera Snapshot_2023-07-08_104445_192 168 1 185

Opera Snapshot_2023-07-08_104507_192 168 1 185

Opera Snapshot_2023-07-08_104627_192 168 1 185

but openplantbook shows:
Opera Snapshot_2023-07-08_105157_open plantbook io

Opera Snapshot_2023-07-08_104544_open plantbook io

ha log:
`2023-07-08 10:47:13.748 DEBUG (MainThread) [custom_components.plant.config_flow] User Input {'name': 'Test', 'species': 'dracaena braunii'}
2023-07-08 10:47:13.748 DEBUG (MainThread) [custom_components.plant.config_flow] Validating step 1: {'name': 'Test', 'species': 'dracaena braunii'}
2023-07-08 10:47:13.748 DEBUG (MainThread) [custom_components.plant.config_flow] Plant_info: {'name': 'Test', 'species': 'dracaena braunii', 'search_for': 'dracaena braunii'}
2023-07-08 10:47:13.748 DEBUG (MainThread) [custom_components.plant.plant_helpers] openplantbook in services? True
2023-07-08 10:47:15.237 DEBUG (MainThread) [custom_components.plant.plant_helpers] openplantbook in services? True
2023-07-08 10:47:15.237 INFO (MainThread) [custom_components.plant.plant_helpers] Did not find 'dracaena braunii' in OpenPlantbook
2023-07-08 10:47:15.237 DEBUG (MainThread) [custom_components.plant.plant_helpers] Parsing input config: {'name': 'Test', 'species': 'dracaena braunii', 'sensors': {}, 'display_pid': None}
2023-07-08 10:47:15.237 DEBUG (MainThread) [custom_components.plant.plant_helpers] Display pid: None
2023-07-08 10:47:15.237 DEBUG (MainThread) [custom_components.plant.plant_helpers] Resulting config: {'data_source': 'Default values', 'plant_info': {'name': 'Test', 'species': 'dracaena braunii', 'entity_picture': '', 'display_pid': '', 'limits': {'max_illuminance': 100000, 'min_illuminance': 0, 'max_conductivity': 3000, 'min_conductivity': 500, 'max_moisture': 60, 'min_moisture': 20, 'max_temperature': 40, 'min_temperature': 10, 'max_humidity': 60, 'min_humidity': 20, 'max_dli': 30, 'min_dli': 2}, 'temperature_sensor': None, 'moisture_sensor': None, 'conductivity_sensor': None, 'illuminance_sensor': None}}
2023-07-08 10:47:15.237 DEBUG (MainThread) [custom_components.plant.plant_helpers] openplantbook in services? True`

### LINKED ISSUE #84: Plant status shows "unknown" for all plants
For some reason all of my plants show status `unknown` 

They are all configured like this one:

image

All of these checked sensors show up and have values:

image

Integration version: 2.2.0-beta1

### LINKED ISSUE #86: 'Unkown error occurred' when adding plant.
Unsure how i got into this situation, but i cant add any more plants for reason: Unkown.

I have 6 plants setup succesfully and working as intended. But when i try to add a new plant now, i simply get 'Unkown error occurred'

Please find the debug log attached. 

[home-assistant_plant_2023-07-18T19-42-19.654Z.log](https://github.com/Olen/homeassistant-plant/files/12088491/home-assistant_plant_2023-07-18T19-42-19.654Z.log)

### PR DESCRIPTION
**Pull request by lkshrk**
- Updated to code to work with [https://github.com/Olen/home-assistant-openplantbook/pull/6](https://github.com/Olen/home-assistant-openplantbook/pull/6).
- Fixes current issues with retrieving data from openplantbook
- Readded timeout for requests to openplantbook
- fixes #86 
- fixes #84
- fixes #82 
- fixes #80

### CODE REVIEW

**Comment by Olen** [comment]
We don't have any way to require the updated plantbook version, do we?

I am currently limited to my phone for reviewing - but did your PR for plantbook remove the sensors and attributes from the results there and just return the data, or does it still create the "sensors" in addition to returning data?

At least we need to tag this as a breaking change as (or "if") the two integrations need to be upgraded simultaneously.

**Comment by lkshrk** [comment]
- We can add the requirement for the new version, [see Docs](https://developers.home-assistant.io/docs/creating_integration_manifest/#dependencies)
> Dependencies are other Home Assistant integrations you want Home Assistant to set up successfully before the integration is loaded. Adding an integration to dependencies will ensure the depending integration is loaded before setup, but it does not guarantee all dependency configuration entries have been set up.
- Since I didn't want to do breaking changes on your behalf, we still use sensors and offer the `return_response` option on top

**Comment by Olen** [comment]
Great.
I did not make this integration depend on Openplantbook on purpose, as some users did not want that. So it is more of a "Openplantbook is optional, but if you want to use it, you need at least version X", which I don't think you can specify.
By releasing both at the same time, and notifying about the soft dependency, I think it is ok.

**Comment by larronni** [comment]
Could you release a new version as well.....?

**Comment by Olen** [comment]
I'll do it in a few days.
I am currently on vacation, and making a release wit only my phone is harder than I thought...

**Pull request merged**
